package NetWork.Message;

public enum MessageType {
    LOGIN_REQUEST,//usato
    LOGIN_RESPONSE,//usato
    REGISTER_REQUEST,//usato
    REGISTER_RESPONSE,//usato
    LOGOUT,//usato
    EXPENSE,//usato
    VIEW_USERNAMES_REQUEST,//usato
    VIEW_USERNAMES_RESPONSE,//usato
    PAYMENT_EXPENSE_REQUEST,//usato
    PAYMENT_EXPENSE_RESPONSE,//usato
    CONSULTATION_EXPENSES_PAID_REQUEST,
    CONSULTATION_EXPENSES_PAID_RESPONSE,
    CONSULTATION_EXPENSES_TO_BE_PAID_REQUEST,
    CONSULTATION_EXPENSES_TO_BE_PAID_RESPONSE,
}
