package NetWork.Message;

public enum MessageType {
    LOGIN_REQUEST,//usato
    LOGIN_RESPONSE,//usato
    REGISTER_REQUEST,//usato
    REGISTER_RESPONSE,//usato
    LOGOUT,//usato
    EXPENSE,//usato
    VIEW_USERNAMES_REQUEST,//usato
    VIEW_USERNAMES_RESPONSE,//usato
    PAYMENT_EXPENSE_REQUEST,//usato
    PAYMENT_EXPENSE_RESPONSE,//usato
    CONSULTATION_EXPENSES_PAID_REQUEST,//usato
    CONSULTATION_EXPENSES_PAID_RESPONSE,//usato
    CONSULTATION_EXPENSES_TO_BE_PAID_REQUEST,//usato
    CONSULTATION_EXPENSES_TO_BE_PAID_RESPONSE,//usato
    CONSULTATION_ALL_EXPENSES_INFORMATION_REQUEST,
    CONSULTATION_ALL_EXPENSES_INFORMATION_RESPONSE,
    CONSULTATION_BALANCE_INFORMATION_REQUEST,
    CONSULTATION_BALANCE_INFORMATION_RESPONSE,
    DELETE_ALL_INFORMATION_REQUEST,//usato
    DELTE_EXPENSES_BALANCE_INFORMATION_REQUEST,//usato
    DELETE_ALL_INFORMATION_RESPONSE,//usato
    DELETE_EXPENSES_BALANCE_INFORMATION_RESPONSE//usato
}
